grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
    path: "/grafana"
    apiVersion: networking.k8s.io/v1
    annotations:
      kubernetes.io/ingress.class: "nginx"
