#Pulling ARM image
controller:
  image: joshuayoung/arm64-jenkins
  tag: "base-2.235.4"
  jenkinsUriPrefix: "/jenkins"

  ingress:
    enabled: true
    paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
    path: "/jenkins"
    apiVersion: networking.k8s.io/v1
    annotations:
      kubernetes.io/ingress.class: "nginx"
