#Values found at https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
#Pulling ARM image
controller:
  image: joshuayoung/arm64-jenkins-k3s-configured
  tag: "2.263.4"
  jenkinsUriPrefix: "/jenkins"

  installPlugins: []
  initializeOnce: true

  nodeSelector:
    kubernetes.io/hostname: k3s-master

  ingress:
    enabled: true
    paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
    path: "/jenkins"
    apiVersion: networking.k8s.io/v1
    annotations:
      kubernetes.io/ingress.class: "nginx"
