pipeline {
  agent any
  environment {
    METALLB_VERSION = "0.1.21"
    KUBE_CONFIG = credentials('PERSONAL-K8S-CLUSTER-CONFIG')
  }

  stages {
    stage('Deploy') {
      steps {

        //Add helm chart
        sh("helm repo add bitnami https://charts.bitnami.com/bitnami")
        sh("helm repo update")

        //Run helm upgrade
        sh("helm upgrade metallb bitnami/metallb --kubeconfig $KUBE_CONFIG --namespace kube-system --install --version $METALLB_VERSION -f ./metallb/helm/values.yaml")
      }
    }
  }
}