pipeline {
  agent any
  environment {
    // Agent will be pulled from https://github.com/jenkinsci/docker-agent by tag
    AGENT_TAG = "4.6-2"
    DOCKERHUB_ORGANISATION = "joshuayoung"
    DOCKERHUB_REPO = "arm64-jenkins-agent"
    DOCKER_USERNAME = "joshuayoung"
    DOCKER_PASSWORD = credentials('DOCKERHUB_PASSWORD')
  }

  stages {
    stage('Build and Push') {
      steps {
      
        //Checkout Jenkins Repo to ./docker-agent (Generated Groovy Script)
        checkout([$class: 'GitSCM', branches: [[name: 'refs/tags/${AGENT_TAG}']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'docker-agent']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/jenkinsci/docker-agent']]])

        //Install docker
        //sh('./jenkins/controller/install-docker.sh')

        //Login to my container repository
        sh('echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin')

        //Initialises build and push
        dir("docker-agent/8/buster") {
          sh('docker build -t $DOCKERHUB_ORGANISATION/$DOCKERHUB_REPO:$AGENT_TAG .');
          sh('docker push $DOCKERHUB_ORGANISATION/$DOCKERHUB_REPO:$AGENT_TAG')
        }
      }
    }
  }
}